export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  VENDOR_NOT_FOUND: "VENDOR_NOT_FOUND",
  ALERT_NOT_FOUND: "ALERT_NOT_FOUND",
  DUPLICATE_ASSIGNMENT: "DUPLICATE_ASSIGNMENT",
  DUPLICATE_CERTIFICATE_NO: "DUPLICATE_CERTIFICATE_NO",
  CERT_EXPIRED: "CERT_EXPIRED",
  CERT_DEVICE_MISMATCH: "CERT_DEVICE_MISMATCH",
  INVALID_PLAN_TRANSITION: "INVALID_PLAN_TRANSITION",
  INVALID_ALERT_TRANSITION: "INVALID_ALERT_TRANSITION"
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
